/* JS */ gapi.loaded_1(function(_){var window=this;
var jz=function(){this.h3={RE:Dl?"../"+Dl:null,zp:Jz,kq:nz,GP:Qz,$f:oz,$P:Bz};this.uu=_.ta;this.Vba=this.gea;this.Aea=/MSIE\s*[0-8](\D|$)/.test(window.navigator.userAgent);if(this.h3.RE){this.uu=this.h3.kq(this.uu,this.h3.RE);var a=this.uu.document,c=a.createElement("script");c.setAttribute("type","text/javascript");c.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(c);this.Vba=this.uu.doPostMsg}this.E9={};this.T9={};a=(0,_.H)(this.p7,
this);_.La(this.uu,"message",a);_.Ka(_.bb,"RPMQ",[]).push(a);this.uu!=this.uu.parent&&CC(this,this.uu.parent,'{"h":"'+escape(this.uu.name)+'"}',"*")},qn=function(a){var c=null;0===a.indexOf('{"h":"')&&a.indexOf('"}')===a.length-2&&(c=unescape(a.substring(6,a.length-2)));return c},kz=function(a){if(!/^\s*{/.test(a))return!1;a=_.of(a);return null!==a&&"object"===typeof a&&!!a.g};
jz.prototype.p7=function(a){var c=String(a.data);(0,_.ke)("gapi.rpc.receive("+Qz+"): "+(!c||512>=c.length?c:c.substr(0,512)+"... ("+c.length+" bytes)"));var f=0!==c.indexOf("!_");f||(c=c.substring(2));var g=kz(c);if(!f&&!g){if(!g&&(f=qn(c))){if(this.E9[f])this.E9[f]();else this.T9[f]=1;return}var h=a.origin,l=this.h3.zp;this.Aea?_.ta.setTimeout(function(){l(c,h)},0):l(c,h)}};jz.prototype.sf=function(a,c){".."===a||this.T9[a]?(c(),delete this.T9[a]):this.E9[a]=c};
var CC=function(a,c,f,g){var h=kz(f)?"":"!_";(0,_.ke)("gapi.rpc.send("+Qz+"): "+(!f||512>=f.length?f:f.substr(0,512)+"... ("+f.length+" bytes)"));a.Vba(c,h+f,g)};jz.prototype.gea=function(a,c,f){a.postMessage(c,f)};jz.prototype.send=function(a,c,f){(a=this.h3.kq(this.uu,a))&&!a.closed&&CC(this,a,c,f)};
var Rz,Hz,pz,uz,Nz,Sz,Pz,Oz,Dl,Qz,Cz,Ez,mz,Gz,nz,oz,qz,rz,yz,xz,zz,Bz,Dz,Fz,tz,vz,Iz,Jz,Kz,Lz;Rz=0;Hz=[];pz={};uz={};Nz=_.R.getUrlParameters;Sz=Nz();Pz=Sz.rpctoken;Oz=Sz.parent||_.ua.referrer;Dl=Sz.rly;Qz=Dl||(_.ta!==_.ta.top||_.ta.opener)&&_.ta.name||"..";Cz=null;Ez={};mz=function(){};Gz={send:mz,sf:mz};
nz=function(a,c){"/"==c.charAt(0)&&(c=c.substring(1),a=_.ta.top);for(c=c.split("/");c.length;){var f=c.shift();"{"==f.charAt(0)&&"}"==f.charAt(f.length-1)&&(f=f.substring(1,f.length-1));if(".."===f)a=a==a.parent?a.opener:a.parent;else if(".."!==f&&a.frames[f]){if(a=a.frames[f],!("postMessage"in a))throw"Not a window";}else return null}return a};oz=function(a){return(a=pz[a])&&a.ve};
qz=function(a){if(a.f in{})return!1;var c=a.t,f=pz[a.r];a=a.origin;return f&&(f.ve===c||!f.ve&&!c)&&(a===f.origin||"*"===f.origin)};rz=function(a){var c=a.id.split("/"),f=c[c.length-1],g=a.origin;return function(h){var l=h.origin;return h.f==f&&(g==l||"*"==g)}};_.sz=function(a,c,f){a=tz(a);uz[a.name]={fn:c,lf:a.lf,Us:f||qz};vz()};_.wz=function(a){delete uz[tz(a).name]};yz={};xz=function(a,c){(a=yz["_"+a])&&a[1](this)&&a[0].call(this,c)};
zz=function(a){var c=a.c;if(!c)return mz;var f=a.r,g=a.g?"legacy__":"";return function(){var h=[].slice.call(arguments,0);h.unshift(f,g+"__cb",null,c);_.Az.apply(null,h)}};Bz=function(a){Cz=a};Dz=function(a){Ez[a]||(Ez[a]=_.ta.setTimeout(function(){Ez[a]=!1;Fz(a)},0))};Fz=function(a){var c=pz[a];if(c&&c.ready){var f=c.kj;for(c.kj=[];f.length;)Gz.send(a,_.mf(f.shift()),c.origin)}};tz=function(a){return 0===a.indexOf("legacy__")?{name:a.substring(8),lf:!0}:{name:a,lf:!1}};
vz=function(){for(var a=_.P("rpc/residenceSec")||60,c=(new Date).getTime()/1E3,f=0,g;g=Hz[f];++f){var h=g.rpc;if(!h||0<a&&c-g.timestamp>a)Hz.splice(f,1),--f;else{var l=h.s,n=uz[l]||uz["*"];if(n)if(Hz.splice(f,1),--f,h.origin=g.origin,g=zz(h),h.callback=g,n.Us(h)){if("__cb"!==l&&!!n.lf!=!!h.g)break;h=n.fn.apply(h,h.a);void 0!==h&&g(h)}else(0,_.ke)("gapi.rpc.rejected("+Qz+"): "+l)}}};Iz=function(a,c,f){Hz.push({rpc:a,origin:c,timestamp:(new Date).getTime()/1E3});f||vz()};
Jz=function(a,c){a=_.of(a);Iz(a,c,!1)};Kz=function(a){for(;a.length;)Iz(a.shift(),this.origin,!0);vz()};Lz=function(a){var c=!1;a=a.split("|");var f=a[0];0<=f.indexOf("/")&&(c=!0);return{id:f,origin:a[1]||"*",Ki:c}};
_.Mz=function(a,c,f,g){var h=Lz(a);g&&(_.ta.frames[h.id]=_.ta.frames[h.id]||g);a=h.id;if(!pz.hasOwnProperty(a)){f=f||null;g=h.origin;if(".."===a)g=_.Rb.getOrigin(Oz),f=f||Pz;else if(!h.Ki){var l=_.ua.getElementById(a);l&&(l=l.src,g=_.Rb.getOrigin(l),f=f||Nz(l).rpctoken)}"*"===h.origin&&g||(g=h.origin);pz[a]={ve:f,kj:[],origin:g,hs:c,xm:function(){var n=a;pz[n].ready=1;Fz(n)}};Gz.sf(a,pz[a].xm)}return pz[a].xm};
_.Az=function(a,c,f,g){a=a||"..";_.Mz(a);a=a.split("|",1)[0];var h=c,l=[].slice.call(arguments,3),n=f,q=Qz,t=Pz,v=pz[a],w=q,A=Lz(a);if(v&&".."!==a){if(A.Ki){if(!(t=pz[a].hs)){t=Cz?Cz.substring(1).split("/"):[Qz];w=t.length-1;for(var F=_.ta.parent;F!==_.ta.top;){var z=F.parent;if(!w--){for(var I=null,E=z.frames.length,K=0;K<E;++K)z.frames[K]==F&&(I=K);t.unshift("{"+I+"}")}F=z}t="/"+t.join("/")}w=t}else w=q="..";t=v.ve}n&&A?(v=qz,A.Ki&&(v=rz(A)),yz["_"+ ++Rz]=[n,v],n=Rz):n=null;l={s:h,f:q,r:w,t:t,c:n,
a:l};h=tz(h);l.s=h.name;l.g=h.lf;pz[a].kj.push(l);Dz(a)};if("function"===typeof _.ta.postMessage||"object"===typeof _.ta.postMessage)Gz=new jz,_.sz("__cb",xz,function(){return!0}),_.sz("_processBatch",Kz,function(){return!0}),_.Mz("..");

_.Fu=function(a){return new _.C(a)};

var pl,Ek,Xz,Zz,Lu,Ku;_.AB.prototype.IZ=_.d(6,function(){return this.Ea.style});_.BB.prototype.IZ=_.d(5,function(){return this.Ea.style});pl=function(a,c){a.Ea.onload=c};_.jN=function(a){a.Ea.closeClickDetection=!0};_.Wb=function(a){return a.Ea.rpctoken};_.Qm=function(a){a.Ea.waitForOnload=!0;return a};Ek=function(a){return(a=a.Ea.timeout)?a:null};_.eb=function(a,c,f){if(a){_.Sa(_.cb(a),"arrayForEach was called with a non array value");for(var g=0;g<a.length;g++)c.call(f,a[g],g)}};
_.fb=function(a,c,f){if(a)if(_.cb(a))_.eb(a,c,f);else{_.Sa("object"===typeof a,"objectForEach was called with a non object value");f=f||a;for(var g in a)_.Qa(a,g)&&void 0!==a[g]&&c.call(f,a[g],g)}};Lu=function(a){this.resolve=this.reject=null;this.promise=_.Fu((0,_.H)(function(c,f){this.resolve=c;this.reject=f},this));a&&(this.promise=Ku(this.promise,a))};Ku=function(a,c){return a.then(function(f){try{c(f)}catch(g){}return f})};
_.yp=function(a){this.Ea=a||{}};_.J(_.yp,_.BB);_.oq=function(a,c){a.Ea.frameName=c;return a};_.yp.prototype.Tp=function(){return this.Ea.frameName};_.Lr=function(a,c){a.Ea.rpcAddr=c;return a};_.yp.prototype.Fl=function(){return this.Ea.rpcAddr};_.Mr=function(a,c){a.Ea.retAddr=c;return a};_.Ss=function(a){return a.Ea.retAddr};_.yp.prototype.Og=function(a){this.Ea.origin=a;return this};_.yp.prototype.getOrigin=function(){return this.Ea.origin};_.yp.prototype.vj=function(a){this.Ea.setRpcReady=a;return this};
_.Yb=function(a){return a.Ea.setRpcReady};_.yp.prototype.Pm=function(a){this.Ea.context=a};var ft=function(a,c){a.Ea._rpcReadyFn=c};_.yp.prototype.rb=function(){return this.Ea.iframeEl};
var co,Wz,Jp;co=/^[\w\.\-]*$/;_.Uz=function(a){return a.Db===a.getContext().Db};_.Vz=function(){return!0};_.AD=function(a){for(var c=_.r(),f=0;f<a.length;f++)c[a[f]]=!0;return function(g){return!!c[g.Db]}};Wz=function(a,c,f){return function(g){if(!c.Oj){_.Sa(this.origin===c.Db,"Wrong origin "+this.origin+" != "+c.Db);var h=this.callback;g=Jp(a,g,c);!f&&0<g.length&&_.Pr(g).then(h)}}};Jp=function(a,c,f){a=Xz[a];if(!a)return[];for(var g=[],h=0;h<a.length;h++)g.push(_.Nu(a[h].call(f,c,f)));return g};
_.Yz=function(a,c,f){_.Sa("_default"!=a,"Cannot update default api");Zz[a]={map:c,filter:f}};_.$z=function(a,c,f){_.Sa("_default"!=a,"Cannot update default api");_.Ka(Zz,a,{map:{},filter:_.Uz}).map[c]=f};_.aA=function(a,c){_.Ka(Zz,"_default",{map:{},filter:_.Vz}).map[a]=c;_.fb(_.Sm.Uv,function(f){f.register(a,c,_.Vz)})};_.jo=function(){return _.Sm};
_.bA=function(a){a=a||{};this.Oj=!1;this.gW=_.r();this.Uv=_.r();this.uu=a._window||_.ta;this.Il=this.uu.location.href;this.Pba=(this.Qba=xu(this.Il,"parent"))?xu(this.Il,"pfname"):"";this.El=this.Qba?xu(this.Il,"_gfid")||xu(this.Il,"id"):"";this.Jh=_.Ln(this.El,this.Pba);this.Db=_.Rb.getOrigin(this.Il);if(this.El){var c=new _.yp;_.Lr(c,a._parentRpcAddr||"..");_.Mr(c,a._parentRetAddr||this.El);c.Og(_.Rb.getOrigin(this.Qba||this.Il));_.oq(c,this.Pba);this.Vb=this.OH(c.value())}else this.Vb=null};
_.k=_.bA.prototype;_.k.Ma=_.b(10);_.k.U=function(){if(!this.Oj){for(var a=0;a<this.Uv.length;a++)this.Uv[a].U();this.Oj=!0}};_.k.Tp=function(){return this.Jh};_.k.Aa=function(){return this.uu};_.k.Wb=function(){return this.uu.document};_.k.sj=_.b(11);_.k.$h=function(a){return this.gW[a]};
_.k.OH=function(a){_.Sa(!this.Oj,"Cannot attach iframe in disposed context");a=new _.yp(a);a.Fl()||_.Lr(a,a.getId());_.Ss(a)||_.Mr(a,"..");a.getOrigin()||a.Og(_.Rb.getOrigin(a.getUrl()));a.Tp()||_.oq(a,_.Ln(a.getId(),this.Jh));var c=a.Tp();if(this.Uv[c])return this.Uv[c];var f=a.Fl(),g=f;a.getOrigin()&&(g=f+"|"+a.getOrigin());var h=_.Ss(a),l=_.Wb(a);l||(l=(l=a.rb())&&(l.getAttribute("data-postorigin")||l.src)||a.getUrl(),l=_.e(l,"rpctoken"));ft(a,_.Mz(g,h,l,a.Ea._popupWindow));g=((window.gadgets||
{}).rpc||{}).setAuthToken;l&&g&&g(f,l);var n=new _.Rm(this,f,c,a),q=a.Ea.messageHandlersFilter;_.fb(a.Ea.messageHandlers,function(t,v){n.register(v,t,q)});_.Yb(a)&&n.vj();_.jA(n,"_g_rpcReady");return n};_.k.CA=function(a){_.oq(a,null);var c=a.getId();!c||co.test(c)&&!this.Aa().document.getElementById(c)||(_.kd("Ignoring requested iframe ID - "+c),a.DD(null))};var xu=function(a,c){var f=_.e(a,c);f||(f=_.of(_.e(a,"jcp",""))[c]);return f||""};
_.bA.prototype.Nf=function(a){_.Sa(!this.Oj,"Cannot open iframe in disposed context");var c=new _.yp(a);rt(this,c);var f=c.Tp();if(f&&this.Uv[f])return this.Uv[f];this.CA(c);f=c.getUrl();_.Sa(f,"No url for new iframe");var g=c.Ea.queryParams||{};g.usegapi="1";_.CN(c,g);g=this.Eaa&&this.Eaa(f,c);g||(g=c.Ea.where,_.Sa(!!g,"No location for new iframe"),f=_.tb(f,g,a),c.Ea.iframeEl=f,g=f.getAttribute("id"));_.Lr(c,g).DD(g);c.Og(_.Rb.getOrigin(c.Ea.eurl||""));this.mba&&this.mba(c,c.rb());f=this.OH(a);f.NA&&
f.NA(f,a);(a=c.Ea.onCreate)&&a(f);c.Ea.disableRelayOpen||f.Ce("_open");return f};
var cA=function(a,c,f){var g=c.Ea.canvasUrl;if(!g)return f;_.Sa(!c.Ea.allowPost&&!c.Ea.forcePost,"Post is not supported when using canvas url");var h=c.getUrl();_.Sa(h&&_.Rb.getOrigin(h)===a.Db&&_.Rb.getOrigin(g)===a.Db,"Wrong origin for canvas or hidden url "+g);c.setUrl(g);_.Qm(c);c.Ea.canvasUrl=null;return function(l){var n=l.Aa(),q=n.location.hash;q=_.Un(h)+(/#/.test(h)?q.replace(/^#/,"&"):q);n.location.replace(q);f&&f(l)}},dA=function(a,c,f){var g=c.Ea.relayOpen;if(g){var h=a.Vb;g instanceof
_.Rm?(h=g,_.Ko(c,0)):0<Number(g)&&_.Ko(c,Number(g)-1);if(h){_.Sa(!!h.DE,"Relaying iframe open is disabled");if(g=c.IZ())if(g=_.eA[g])c.Pm(a),g(c.value()),c.Pm(null);c.Ea.openerIframe=null;f.resolve(h.DE(c));return!0}}return!1},fA=function(a,c,f){var g=c.IZ();if(g)if(_.Sa(!!_.gA,"Defer style is disabled, when requesting style "+g),_.hA[g])rt(a,c);else return iA(g,function(){_.Sa(!!_.hA[g],"Fail to load style - "+g);f.resolve(a.open(c.value()))}),!0;return!1};
_.bA.prototype.open=function(a,c){_.Sa(!this.Oj,"Cannot open iframe in disposed context");var f=new _.yp(a);c=cA(this,f,c);var g=new Lu(c);(c=f.getUrl())&&f.setUrl(_.Un(c));if(dA(this,f,g)||fA(this,f,g)||dA(this,f,g))return g.promise;if(null!=Ek(f)){var h=setTimeout(function(){n.rb().src="about:blank";g.reject({timeout:"Exceeded time limit of :"+Ek(f)+"milliseconds"})},Ek(f)),l=g.resolve;g.resolve=function(q){clearTimeout(h);l(q)}}f.Ea.waitForOnload&&pl(f.Wp(),function(){g.resolve(n)});var n=this.Nf(a);
f.Ea.waitForOnload||g.resolve(n);return g.promise};_.bA.prototype.taa=_.b(12);_.Rm=function(a,c,f,g){this.Oj=!1;this.Yf=a;this.Nc=c;this.Jh=f;this.jA=g;this.re=_.Ss(this.jA);this.Db=this.jA.getOrigin();this.iK=this.jA.rb();this.vF=this.jA.Ea.where;this.$o=[];this.Ce("_default");a=this.jA.Ea.apis||[];for(c=0;c<a.length;c++)this.Ce(a[c]);this.Yf.Uv[f]=this};_.k=_.Rm.prototype;_.k.Ma=_.b(9);
_.k.U=function(){if(!this.Oj){for(var a=0;a<this.$o.length;a++)this.unregister(this.$o[a]);delete _.Sm.Uv[this.Tp()];this.Oj=!0}};_.k.getContext=function(){return this.Yf};_.k.Fl=function(){return this.Nc};_.k.Tp=function(){return this.Jh};_.k.rb=function(){return this.iK};_.k.V=function(){return this.vF};_.k.qc=function(a){this.vF=a};_.k.vj=function(){(0,this.jA.Ea._rpcReadyFn)()};_.k.Vm=function(a,c){this.jA.value()[a]=c};_.k.Zf=function(a){return this.jA.value()[a]};_.k.va=function(){return this.jA.value()};
_.k.getId=function(){return this.jA.getId()};_.k.getOrigin=function(){return this.Db};_.k.register=function(a,c,f){_.Sa(!this.Oj,"Cannot register handler on disposed iframe "+a);_.Sa((f||_.Uz)(this),"Rejecting untrusted message "+a);f=this.Jh+":"+this.Yf.Jh+":"+a;1==_.Ka(Xz,f,[]).push(c)&&(this.$o.push(a),_.sz(f,Wz(f,this,"_g_wasClosed"===a)))};
_.k.unregister=function(a,c){var f=this.Jh+":"+this.Yf.Jh+":"+a,g=Xz[f];g&&(c?(c=_.xd.call(g,c),0<=c&&g.splice(c,1)):g.splice(0,g.length),0==g.length&&(c=_.xd.call(this.$o,a),0<=c&&this.$o.splice(c,1),_.wz(f)))};_.k.fq=function(){return this.$o};_.k.Ce=function(a){this.Sy=this.Sy||[];if(!(0<=_.xd.call(this.Sy,a))){this.Sy.push(a);a=Zz[a]||{map:{}};for(var c in a.map)_.Qa(a.map,c)&&this.register(c,a.map[c],a.filter)}};
_.k.send=function(a,c,f,g){_.Sa(!this.Oj,"Cannot send message to disposed iframe - "+a);_.Sa((g||_.Uz)(this),"Wrong target for message "+a);f=new Lu(f);_.Az(this.Nc,this.Yf.Jh+":"+this.Jh+":"+a,f.resolve,c);return f.promise};_.jA=function(a,c,f,g){return a.send(c,f,g,_.Vz)};_.Rm.prototype.aL=function(a){return a};_.Rm.prototype.ping=function(a,c){return _.jA(this,"_g_ping",c,a)};Xz=_.r();Zz=_.r();_.Sm=new _.bA;_.aA("_g_rpcReady",_.Rm.prototype.vj);_.aA("_g_discover",_.Rm.prototype.fq);
_.aA("_g_ping",_.Rm.prototype.aL);
var iA,rt;_.hA=_.r();_.eA=_.r();_.gA=function(a){return _.hA[a]};iA=function(a,c){_.Ua.load("gapi.iframes.style."+a,c)};rt=function(a,c){var f=c.IZ();if(f){c.rl(null);var g=_.hA[f];_.Sa(g,"No such style: "+f);c.Pm(a);g(c.value());c.Pm(null)}};
var nA,oA;nA={height:!0,width:!0};oA=/^(?!-*(?:expression|(?:moz-)?binding))(?:[.#]?-?(?:[_a-z0-9-]+)(?:-[_a-z0-9-]+)*-?|-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[a-z]{1,2}|%)?|!important|)$/i;_.no=function(a){"number"===typeof a&&(a=String(a)+"px");return a};_.Rm.prototype.Aa=function(){if(!_.Uz(this))return null;var a=this.jA.Ea._popupWindow;if(a)return a;var c=this.Nc.split("/");a=this.getContext().Aa();for(var f=0;f<c.length&&a;f++){var g=c[f];a=".."===g?a==a.parent?a.opener:a.parent:a.frames[g]}return a};
var lA=function(a,c){var f=a.Vb,g=!0;c.filter&&(g=c.filter.call(c.qg,c.params));return _.Nu(g).then(function(h){return h&&f?(c.um&&c.um.call(a,c.params),h=c.sender?c.sender(c.params):_.jA(f,c.message,c.params),c.Kz?h.then(function(){return!0}):!0):!1})};
_.bA.prototype.s6=function(a,c,f){a=lA(this,{sender:function(g){var h=_.Sm.Vb;_.fb(_.Sm.Uv,function(l){l!==h&&_.jA(l,"_g_wasClosed",g)});return _.jA(h,"_g_closeMe",g)},message:"_g_closeMe",params:a,qg:f,filter:this.$h("onCloseSelfFilter")});c=new Lu(c);c.resolve(a);return c.promise};_.bA.prototype.Y8=function(a,c,f){a=a||{};c=new Lu(c);c.resolve(lA(this,{message:"_g_restyleMe",params:a,qg:f,filter:this.$h("onRestyleSelfFilter"),Kz:!0,um:this.$ca}));return c.promise};
_.bA.prototype.$ca=function(a){"auto"===a.height&&(a.height=_.Ob.getHeight())};_.mA=function(a){var c={};if(a)for(var f in a)_.Qa(a,f)&&_.Qa(nA,f)&&oA.test(a[f])&&(c[f]=a[f]);return c};_.k=_.Rm.prototype;_.k.close=function(a,c){return _.jA(this,"_g_close",a,c)};_.k.sD=function(a,c){return _.jA(this,"_g_restyle",a,c)};_.k.ds=function(a,c){return _.jA(this,"_g_restyleDone",a,c)};_.k.qp=function(a){return this.getContext().s6(a,void 0,this)};
_.k.tD=function(a){if(a&&"object"===typeof a)return this.getContext().Y8(a,void 0,this)};_.k.mu=function(a){var c=this.jA.Ea.onRestyle;c&&c.call(this,a,this);a=a&&"object"===typeof a?_.mA(a):{};(c=this.rb())&&a&&"object"===typeof a&&(_.Qa(a,"height")&&(a.height=_.no(a.height)),_.Qa(a,"width")&&(a.width=_.no(a.width)),_.Sl(a,c.style))};
_.k.rp=function(a){var c=this.jA.Ea.onClose;c&&c.call(this,a,this);this.BC&&this.BC()||(c=this.rb())&&c.parentNode&&c.parentNode.removeChild(c);if(c=this.jA.Ea.controller){var f={};f.frameName=this.Tp();_.jA(c,"_g_disposeControl",f)}Jp(this.Jh+":"+this.Yf.Jh+":_g_wasClosed",a,this)};_.bA.prototype.rca=_.b(13);_.bA.prototype.xca=_.b(14);_.Rm.prototype.QE=_.b(15);_.Rm.prototype.PE=function(a,c){this.register("_g_wasClosed",a,c)};
_.Rm.prototype.pM=function(){delete this.getContext().Uv[this.Tp()];this.getContext().Aa().setTimeout((0,_.H)(function(){this.U()},this),0)};_.aA("_g_close",_.Rm.prototype.qp);_.aA("_g_closeMe",_.Rm.prototype.rp);_.aA("_g_restyle",_.Rm.prototype.tD);_.aA("_g_restyleMe",_.Rm.prototype.mu);_.aA("_g_wasClosed",_.Rm.prototype.pM);

var Tu,$v,fB,bB;_.BB.prototype.H0=_.d(8,function(a){this.Ea.apis=a;return this});_.BB.prototype.oZ=_.d(7,function(a){this.Ea.rpctoken=a;return this});_.Pu=function(a,c){a.Ea.onClose=c;return a};_.kv=function(a){this.Ea=a||{}};_.kv.prototype.value=function(){return this.Ea};_.kv.prototype.getIframe=function(){return this.Ea.iframe};_.lv=function(a,c){a.Ea.role=c;return a};_.kv.prototype.vj=function(a){this.Ea.setRpcReady=a;return this};_.kv.prototype.oZ=function(a){this.Ea.rpctoken=a;return this};
_.tB=function(a){a.Ea.selfConnect=!0;return a};Tu=function(a){this.Ea=a||{}};Tu.prototype.value=function(){return this.Ea};var Kv=function(a){var c=new Tu;c.Ea.role=a;return c};Tu.prototype.e4=function(){return this.Ea.role};Tu.prototype.Mo=function(a){this.Ea.handler=a;return this};Tu.prototype.Cr=function(){return this.Ea.handler};var Ii=function(a,c){a.Ea.filter=c;return a};Tu.prototype.H0=function(a){this.Ea.apis=a;return this};$v=function(a){a.Ea.runOnce=!0;return a};fB=/^https?:\/\/[^\/%\\?#\s]+$/i;
bB={longdesc:!0,name:!0,src:!0,frameborder:!0,marginwidth:!0,marginheight:!0,scrolling:!0,align:!0,height:!0,width:!0,id:!0,"class":!0,title:!0,tabindex:!0,hspace:!0,vspace:!0,allowtransparency:!0};_.ZA=function(a,c,f){var g=a.Nc,h=c.re;_.Mr(_.Lr(f,a.re+"/"+c.Nc),h+"/"+g);_.oq(f,c.Tp()).Og(c.Db)};_.bA.prototype.u6=_.b(16);_.k=_.Rm.prototype;
_.k.$H=function(a){var c=new _.yp(a);a=new _.kv(c.value());if(a.Ea.selfConnect)var f=this;else(_.Sa(fB.test(c.getOrigin()),"Illegal origin for connected iframe - "+c.getOrigin()),f=this.Yf.Uv[c.Tp()],f)?_.Yb(c)&&(f.vj(),_.jA(f,"_g_rpcReady")):(c=_.oq(_.Mr(_.Lr((new _.yp).oZ(_.Wb(c)),c.Fl()),_.Ss(c)).Og(c.getOrigin()),c.Tp()).vj(_.Yb(c)),f=this.Yf.OH(c.value()));c=this.Yf;var g=a.Ea.role;a=a.Ea.data;dB(c);g=g||"";_.Ka(c.v6,g,[]).push({qg:f.Tp(),data:a});eB(f,a,c.m8[g])};
_.k.NA=function(a,c){(new _.yp(c)).Ea._relayedDepth||(c={},_.tB(_.lv(new _.kv(c),"_opener")),_.jA(a,"_g_connect",c))};
_.k.DE=function(a){var c=this,f=a.Ea.messageHandlers,g=a.Ea.messageHandlersFilter,h=a.Ea.onClose;_.Pu(_.AN(_.BN(a,null),null),null);_.Su();return _.jA(this,"_g_open",a.value()).then(function(l){var n=new _.yp(l[0]),q=n.Tp();l=new _.yp;var t=c.re,v=_.Ss(n);_.Mr(_.Lr(l,c.Nc+"/"+n.Fl()),v+"/"+t);_.oq(l,q);l.Og(n.getOrigin());l.H0(n.Ea.apis);l.oZ(_.Wb(a));_.BN(l,f);_.AN(l,g);_.Pu(l,h);(n=c.Yf.Uv[q])||(n=c.Yf.OH(l.value()));return n})};
_.k.CA=function(a){var c=a.getUrl();_.Sa(!c||_.Ie.test(c),"Illegal url for new iframe - "+c);var f=a.Wp().value();c={};for(var g in f)_.Qa(f,g)&&_.Qa(bB,g)&&(c[g]=f[g]);_.Qa(f,"style")&&(g=f.style,"object"===typeof g&&(c.style=_.mA(g)));a.value().attributes=c};
_.k.VK=function(a){a=new _.yp(a);this.CA(a);var c=a.Ea._relayedDepth||0;a.Ea._relayedDepth=c+1;a.Ea.openerIframe=this;_.Su();var f=_.Wb(a);a.oZ(null);return this.Yf.open(a.value()).then((0,_.H)(function(g){var h=(new _.yp(g.va())).Ea.apis,l=new _.yp;_.ZA(g,this,l);0==c&&_.lv(new _.kv(l.value()),"_opener");l.vj(!0);l.oZ(f);_.jA(g,"_g_connect",l.value());l=new _.yp;_.oq(_.Mr(_.Lr(l.H0(h),g.Fl()),g.re),g.Tp()).Og(g.getOrigin());return l.value()},this))};var dB=function(a){a.v6||(a.v6=_.r(),a.m8=_.r())};
_.bA.prototype.p3=function(a,c,f,g){dB(this);"object"===typeof a?(c=new Tu(a),f=c.e4()||""):(c=Ii(Kv(a).Mo(c).H0(f),g),f=a);g=this.v6[f]||[];a=!1;for(var h=0;h<g.length&&!a;h++)eB(this.Uv[g[h].qg],g[h].data,[c]),a=c.Ea.runOnce;f=_.Ka(this.m8,f,[]);a||c.Ea.dontWait||f.push(c)};_.bA.prototype.dca=_.b(17);
var eB=function(a,c,f){f=f||[];for(var g=0;g<f.length;g++){var h=f[g];if(h&&a){var l=h.Ea.filter||_.Uz;if(a&&l(a)){l=h.Ea.apis||[];for(var n=0;n<l.length;n++)a.Ce(l[n]);h.Cr()&&h.Cr()(a,c);h.Ea.runOnce&&(f.splice(g,1),--g)}}}};_.bA.prototype.a1=function(a,c,f){this.p3($v(Ii(Kv("_opener").Mo(a).H0(c),f)).value())};_.Rm.prototype.pL=function(a){this.getContext().a1(function(c){c.send("_g_wasRestyled",a,void 0,_.Vz)},null,_.Vz)};var gB=_.Sm.Vb;gB&&gB.register("_g_restyleDone",_.Rm.prototype.pL,_.Vz);
_.aA("_g_connect",_.Rm.prototype.$H);var hB={};hB._g_open=_.Rm.prototype.VK;_.Yz("_open",hB,_.Vz);

_.Mu("gapi.iframes.create",_.tb);

_.Rm.prototype.QE=_.d(15,function(a,c){this.register("_g_wasRestyled",a,c)});_.k=_.bA.prototype;_.k.xca=_.d(14,function(a){this.sj("onRestyleSelfFilter",a)});_.k.rca=_.d(13,function(a){this.sj("onCloseSelfFilter",a)});_.k.taa=_.d(12,function(){return this.Vb});_.k.sj=_.d(11,function(a,c){this.gW[a]=c});_.k.Ma=_.d(10,function(){return this.Oj});_.Rm.prototype.Ma=_.d(9,function(){return this.Oj});_.Mu("gapi.iframes.registerStyle",function(a,c){_.hA[a]=c});
_.Mu("gapi.iframes.registerBeforeOpenStyle",function(a,c){_.eA[a]=c});_.Mu("gapi.iframes.getStyle",_.gA);_.Mu("gapi.iframes.getBeforeOpenStyle",function(a){return _.eA[a]});_.Mu("gapi.iframes.registerIframesApi",_.Yz);_.Mu("gapi.iframes.registerIframesApiHandler",_.$z);_.Mu("gapi.iframes.getContext",_.jo);_.Mu("gapi.iframes.SAME_ORIGIN_IFRAMES_FILTER",_.Uz);_.Mu("gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.Vz);_.Mu("gapi.iframes.makeWhiteListIframesFilter",_.AD);_.Mu("gapi.iframes.Context",_.bA);
_.Mu("gapi.iframes.Context.prototype.isDisposed",_.bA.prototype.Ma);_.Mu("gapi.iframes.Context.prototype.getWindow",_.bA.prototype.Aa);_.Mu("gapi.iframes.Context.prototype.getFrameName",_.bA.prototype.Tp);_.Mu("gapi.iframes.Context.prototype.getGlobalParam",_.bA.prototype.$h);_.Mu("gapi.iframes.Context.prototype.setGlobalParam",_.bA.prototype.sj);_.Mu("gapi.iframes.Context.prototype.open",_.bA.prototype.open);_.Mu("gapi.iframes.Context.prototype.openChild",_.bA.prototype.Nf);
_.Mu("gapi.iframes.Context.prototype.getParentIframe",_.bA.prototype.taa);_.Mu("gapi.iframes.Context.prototype.closeSelf",_.bA.prototype.s6);_.Mu("gapi.iframes.Context.prototype.restyleSelf",_.bA.prototype.Y8);_.Mu("gapi.iframes.Context.prototype.setCloseSelfFilter",_.bA.prototype.rca);_.Mu("gapi.iframes.Context.prototype.setRestyleSelfFilter",_.bA.prototype.xca);_.Mu("gapi.iframes.Iframe",_.Rm);_.Mu("gapi.iframes.Iframe.prototype.isDisposed",_.Rm.prototype.Ma);
_.Mu("gapi.iframes.Iframe.prototype.getContext",_.Rm.prototype.getContext);_.Mu("gapi.iframes.Iframe.prototype.getFrameName",_.Rm.prototype.Tp);_.Mu("gapi.iframes.Iframe.prototype.getId",_.Rm.prototype.getId);_.Mu("gapi.iframes.Iframe.prototype.register",_.Rm.prototype.register);_.Mu("gapi.iframes.Iframe.prototype.unregister",_.Rm.prototype.unregister);_.Mu("gapi.iframes.Iframe.prototype.send",_.Rm.prototype.send);_.Mu("gapi.iframes.Iframe.prototype.applyIframesApi",_.Rm.prototype.Ce);
_.Mu("gapi.iframes.Iframe.prototype.getIframeEl",_.Rm.prototype.rb);_.Mu("gapi.iframes.Iframe.prototype.getSiteEl",_.Rm.prototype.V);_.Mu("gapi.iframes.Iframe.prototype.setSiteEl",_.Rm.prototype.qc);_.Mu("gapi.iframes.Iframe.prototype.getWindow",_.Rm.prototype.Aa);_.Mu("gapi.iframes.Iframe.prototype.getOrigin",_.Rm.prototype.getOrigin);_.Mu("gapi.iframes.Iframe.prototype.close",_.Rm.prototype.close);_.Mu("gapi.iframes.Iframe.prototype.restyle",_.Rm.prototype.sD);
_.Mu("gapi.iframes.Iframe.prototype.restyleDone",_.Rm.prototype.ds);_.Mu("gapi.iframes.Iframe.prototype.registerWasRestyled",_.Rm.prototype.QE);_.Mu("gapi.iframes.Iframe.prototype.registerWasClosed",_.Rm.prototype.PE);_.Mu("gapi.iframes.Iframe.prototype.getParam",_.Rm.prototype.Zf);_.Mu("gapi.iframes.Iframe.prototype.setParam",_.Rm.prototype.Vm);_.Mu("gapi.iframes.Iframe.prototype.ping",_.Rm.prototype.ping);

var mv=function(a,c){a.Ea.data=c;return a};_.bA.prototype.dca=_.d(17,function(a,c){a=_.Ka(this.m8,a,[]);if(c)for(var f=0,g=!1;!g&&f<a.length;f++)a[f].Tc===c&&(g=!0,a.splice(f,1));else a.splice(0,a.length)});
_.bA.prototype.u6=_.d(16,function(a,c){a=new _.kv(a);var f=new _.kv(c),g=_.Yb(a);c=a.getIframe();var h=f.getIframe();if(h){var l=_.Wb(a),n=new _.yp;_.ZA(c,h,n);mv(_.lv((new _.kv(n.value())).oZ(l),a.Ea.role),a.Ea.data).vj(g);var q=new _.yp;_.ZA(h,c,q);mv(_.lv((new _.kv(q.value())).oZ(l),f.Ea.role),f.Ea.data).vj(!0);_.jA(c,"_g_connect",n.value(),function(){g||_.jA(h,"_g_connect",q.value())});g&&_.jA(h,"_g_connect",q.value())}else f={},mv(_.lv(_.tB(new _.kv(f)),a.Ea.role),a.Ea.data),_.jA(c,"_g_connect",
f)});_.Mu("gapi.iframes.Context.prototype.addOnConnectHandler",_.bA.prototype.p3);_.Mu("gapi.iframes.Context.prototype.removeOnConnectHandler",_.bA.prototype.dca);_.Mu("gapi.iframes.Context.prototype.addOnOpenerHandler",_.bA.prototype.a1);_.Mu("gapi.iframes.Context.prototype.connectIframes",_.bA.prototype.u6);

});
// Google Inc.
